version: '2.3'

x-common: &common
  image: hairyhenderson/trx:arm
  restart: always
  privileged: true
  ulimits:
    rtprio: 25
  devices:
    - /dev/snd:/dev/snd
  network_mode: host

services:
  lrad-to-rrpt:
    <<: *common
    command: tx -d plughw:CARD=Device,DEV=0 -h 10.0.1.22 -c 1 -r 48000 -f 480
    labels:
      description: Input from the local radio, transmit to the remote repeater
  rrad-to-lrpt:
    <<: *common
    command: rx -d plughw:CARD=Device,DEV=0 -c 1 -r 48000 -j 60
    labels:
      description: Receive from the remote radio, output to the local repeater
